### ISSUE TITLE
Proposed Contribution:  add Greenfield SDK Proto

### ISSUE THREAD

**Issue by ive663** [bnb-chain/awesome#8]
Hello,

I hope you're doing well. I noticed that the main contributor of this project haven't been active for some time. I'm interested in contributing to the project and would like to propose some changes. 

I have already forked the repository and made the necessary modifications on my local machine. I have created a new branch called "add Greenfield SDK Proto" where these changes are committed. 

I have also submitted a pull request with the details of my changes. It would be great if you could review and consider merging my pull request into the main project.

Please let me know if there is anything else I can do or if you have any specific guidelines for contributing to the project. I'm excited to be a part of this project and contribute to its development.

Thank you!

Best regards,
ive663

**Comment by deepcrazy** [comment]
Hi there, Thanks for contributing. 

I think we have already discussed regarding this in discord and have suggested you to open the proposal in the forum: https://forum.bnbchain.org/c/bnb-greenfield/25 for the community with all the in-depth technical details of your project/SDK (using rust) and its usage. 
Please also do share your project/repo link in the forum.
Thanks.

**Comment by ive663** [comment]
done...
https://forum.bnbchain.org/t/proposal-add-greenfield-rust-sdk-to-bnbchain-awesome/1575

**Comment by deepcrazy** [comment]
Thanks! I would also recommend you to provide more details if possible in the forum post. Please also include your main repo URL: https://github.com/ive663/ChainSauce_task1 which has README.md and its usage in the form of commands as a reference for the community.
